config/routes.rb
Rails.application.routes.draw do
  root 'landing#landing'
  get 'cameo', to: 'homes#index', as: 'cameo'
  get 'category', to: 'homes#category', as: 'category'
  get 'user_detail/:id', to: 'homes#user_detail', as: 'user_detail'
  get 'back', to: 'homes#back', as: 'back'
  get "search_user", to: 'homes#search_user', as: 'search_user'
  post 'execute_crawl', to: 'homes#execute_crawl', as: 'execute_crawl'
  get 'category_detail/:id', to: 'homes#category_detail', as: 'category_detail'
  get 'export_xlsx', to: 'export_data#execute', as: 'export_xlsx'
  get 'export_data', to: 'export_data#index', as: 'export_data'
  get 'statistic', to: 'statistic_star#index', as: 'statistic'
  post 'statistic_search', to: 'statistic_star#search', as: 'statistic_search'
  get 'celebvm', to: 'homes#celebvm', as: 'celebvm'
  get 'category_celebvm', to: 'homes#category_celebvm', as: 'category_celebvm'
  get 'category_celebvm_detail/:id', to: 'homes#category_celebvm_detail', as: 'category_celebvm_detail'
  get 'user_celebvm_detail/:id', to: 'homes#user_celebvm_detail', as: 'user_celebvm_detail'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tallent_categories
  has_many :users, through: :tallent_categories

  scope :get_cameos, -> {where type_web: "cameo"}
  scope :get_celebvms, -> {where type_web: "celebvm"}

  def self.search(start_time, end_time, type_web)
    results = get_cameos if type_web == "cameo"
    results = get_celebvms if type_web == "celebvm"

    results.where("users.created_at >= ? and users.created_at <= ?", start_time, end_time).references(:users)
  end
end

app/models/status_crawl.rb
class StatusCrawl < ApplicationRecord
end

app/models/tallent_category.rb
class TallentCategory < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tallent_categories
  has_many :categories, through: :tallent_categories

  scope :get_cameos, -> {where type_web: "cameo"}
  scope :get_celebvms, -> {where type_web: "celebvm"}

  def self.sort_user(condition)
    users = self.includes(:categories)
    users = users.where("name like ? or username like ?", "%#{condition['keyword']}%", "%#{condition['keyword']}%") if condition['keyword'].present?
    users = users.order(created_at: condition["created_at"]) if condition["created_at"].present?
    return users.order(name: condition["name"]) if condition["name"].present?
    return users.order(numOfRatings: condition["numOfRatings"]) if condition["numOfRatings"].present?
    users
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include HttpAuthConcern
  include Pagy::Backend
end

app/controllers/concerns/http_auth_concern.rb
module HttpAuthConcern
  extend ActiveSupport::Concern
  included do
    before_action :http_authenticate
  end

  def http_authenticate
    return true unless Rails.env == 'production'
    authenticate_or_request_with_http_basic do |username, password|
      username == Rails.application.credentials.auth[:username] && password == Rails.application.credentials.auth[:password]
    end
  end
end

app/controllers/export_data_controller.rb
class ExportDataController < ApplicationController
  def index; end

  def execute
    if !params["name_file"].present?
      flash[:notice] = "Your File Name isn't blank"
      redirect_to export_data_path and return
    end
    if !params["type"].present?
      flash[:notice] = "Please choose type user"
      redirect_to export_data_path and return
    end

    users = params["type"] === "cameo" ? User.get_cameos : User.get_celebvms
    axlsx = CameoAxlsx.new(users, params["name_file"], params["name_sheet"], params["type"])
    axlsx.execute
    file_xlsx = File.join("#{Rails.root}/public/excel/#{params['name_file']}.xlsx")
    send_file file_xlsx, :disposition => 'inline' rescue ""
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_user, only: [:user_detail]
  before_action :check_crawl, only: [:crawl, :execute_crawl]

  layout 'crawler'

  def index
    @pagy, @users = pagy(User.sort_user(params).get_cameos)
  end

  def celebvm
    @pagy, @users = pagy(User.sort_user(params).get_celebvms)
  end

  def crawl
    return if @statuses.present?

    StatusCrawl.create(current_status: 'new', name: 'cameo')
    StatusCrawl.create(current_status: 'new', name: 'celebvm')
    @statuses = StatusCrawl.all
  end

  def execute_crawl
    status = @statuses.find_by(name: params["type"])
    if status.present? && status.current_status == "running"
      return redirect_to root_path, notice: "There is a crawl #{@status.name} running, please waiting for a moment"
    end

    if params["type"] == "cameo"
      status.update({current_status: "running", name: params["type"]})
      CameoJobJob.perform_later
    else
      status.update({current_status: "running", name: params["type"]})
      CelebvmJobJob.perform_later
    end

    respond_to do |format|
      format.js
    end
  end

  def category_detail
    @category = Category.find_by(id: params[:id])
    @pagy, @users = pagy(@category.users)
  end

  def category_celebvm_detail
    @category = Category.find_by(id: params[:id])
    @pagy, @users = pagy(@category.users)
  end

  def user_detail; end

  def user_celebvm_detail
    @user = User.find_by(id: params["id"])
  end

  def back
    redirect_back(fallback_location: root_path)
  end

  def category
    @pagy, @categories = pagy(Category.all.includes(:users).get_cameos)
  end

  def category_celebvm
    @pagy, @categories = pagy(Category.all.includes(:users).get_celebvms)
  end

  private
  def set_user
    @user = User.find_by(_id: params["id"])
  end

  def check_crawl
    @statuses = StatusCrawl.all
  end
end

app/controllers/statistic_star_controller.rb
class StatisticStarController < ApplicationController
  before_action :set_params

  def index
    @type = params["type"] ? params["type"] : "cameo"
    @pagy, @categories = pagy(Category.all.includes(:users).search(@start_time, @end_time, @type))
  end

  private
  def set_params
    if params["date_range"].present?
      datetime = params["date_range"].split("-").map(&:squish).map(&:to_datetime)
      @start_time = datetime.dig(0)
      @end_time = datetime.dig(1)
    else
      @start_time = Date.today.beginning_of_week
      @end_time = Date.today.end_of_week
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def datetime_range(start_week, end_week)
    return if !start_week.present? || !end_week.present?
    "#{start_week.strftime('%d/%m/%Y')} - #{end_week.strftime('%d/%m/%Y')}"
  end
end

app/helpers/export_data_helper.rb
module ExportDataHelper
end

app/helpers/homes_helper.rb
module HomesHelper
  def show_category(categories)
    content_tag(:ul) do
      categories.each do |item|
        concat content_tag(:li, item.name)
      end
    end
  end

  def temporarilyUnavailable?(data)
    data ? "active" : "inactive"
  end
end

app/helpers/statistic_star_helper.rb
module StatisticStarHelper
end

app/views/export_data/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <% if flash["notice"] %>
      <div class="alert alert-danger">
        <strong>Danger!</strong> <%= flash["notice"] %>
      </div>
    <% end %>
    <h1 class="display-3 text-center">Start export excel</h1>
    <p class="lead">
      <%= form_with url: export_xlsx_path, class: "text-center", method: :get, local: true do |form| %>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Select type:</label>
          <div class="col-sm-10">
            <%= form.select :type, options_for_select([ "cameo", "celebvm" ], params["type"]), {prompt: "Choose type"}, {class: "form-control width-select"} %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">File Name:</label>
          <div class="col-sm-10">
            <%= form.text_field :name_file, class: "form-control" %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Sheet Name:</label>
          <div class="col-sm-10">
            <%= form.text_field :name_sheet, class: "form-control" %>
          </div>
        </div>
        <%= form.submit "Export", class: "btn btn-primary btn-lg", data: { disable_with: false } %>
      <% end %>
    </p>
  </div>
</div>

app/views/homes/_status.html.erb
<% statuses.each do |status| %>
  <div class="text-center"><%= status&.name&.capitalize %> crawl last time: <%= status.current_status != "new" ? status.updated_at : "no crawl" %></div>
  <div>
    <% if status.current_status == "new" %>
      <h4 class="text-center">Status: <%= status&.name&.capitalize %> IS NEW</h4>
    <% elsif status.current_status == "running" %>
      <h4 class="text-center color-red">Status: <%= status&.name&.capitalize %> IS RUNNING</h4>
    <% else %>
      <h4 class="text-center color-green">Status: <%= status&.name&.capitalize %> FINISHED</h4>
    <% end %>
  </div>
<% end %>

app/views/homes/category.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <table class="table table-bordered">
      <thead class="thead-inverse">
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Number of persons</th>
        </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td scope="row"><%= link_to category.id, category_detail_path(category) %></td>
              <td><%= category.name %></td>
              <td><%= category.users&.size %></td>
            </tr>
          <% end %>
        </tbody>
    </table>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 custom-pagy">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/homes/category_celebvm.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <table class="table table-bordered">
      <thead class="thead-inverse">
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Number of persons</th>
        </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td scope="row"><%= link_to category.id, category_celebvm_detail_path(category) %></td>
              <td><%= category.name %></td>
              <td><%= category.users&.size %></td>
            </tr>
          <% end %>
        </tbody>
    </table>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 custom-pagy">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/homes/category_celebvm_detail.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <table class="table table-bordered">
      <thead class="thead-inverse">
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Price</th>
          <th>Image</th>
          <th>Category</th>
        </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= link_to user.id, user_celebvm_detail_path(user.id) %></td>
              <td><%= user.name %></td>
              <td><%= "$ #{user.price}" %></td>
              <td><%= image_tag user.imageUrl, class: "rounded-circle image" %></td>
              <td><%= show_category(user.categories) %></td>
            </tr>
          <% end %>
        </tbody>
    </table>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 custom-pagy">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/homes/category_detail.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <table class="table table-bordered">
      <thead class="thead-inverse">
        <tr>
          <th>_id</th>
          <th>Name</th>
          <th>numOfRatings</th>
          <th>Image</th>
          <th>Category</th>
        </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= link_to user._id, user_detail_path(user._id) %></td>
              <td><%= user.name %></td>
              <td><%= user.numOfRatings %></td>
              <td><%= image_tag user.imageUrl, class: "rounded-circle image" %></td>
              <td><%= show_category(user.categories) %></td>
            </tr>
          <% end %>
        </tbody>
    </table>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 custom-pagy">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/homes/celebvm.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 wrap-search-box">
    <%= form_with url: celebvm_path, method: :get, local: true, id: "id_form_search", class: "form-inline my-2 my-lg-0" do |form| %>
      <%= form.text_field :keyword, value: params["keyword"], id: "id_keyword", class: "form-control mr-sm-2", placeholder: "Enter name" %>
      <%= form.submit "Search", class: "btn btn-outline-success my-2 my-sm-0", id: "id_submit_search", data: { disable_with: false } %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <%= form_tag celebvm_path, method: :get, id: "id_form_user" do %>
    <table class="table table-bordered">
      <thead class="thead-inverse">
        <tr>
          <th><%= select_tag :name, options_for_select([
              {name: "DESC", id: "desc"}, {name: "ASC", id: "asc"}].map { |obj| [obj[:name], obj[:id]] }, params["name"]), prompt: "Name", id: "id_sort_name" %></th>
          <th>Price</th>
          <th>Image</th>
          <th>Category</th>
          <th>
            <%= select_tag :created_at, options_for_select([
            {name: "DESC", id: "desc"}, {name: "ASC", id: "asc"}].map { |obj| [obj[:name], obj[:id]] }, params["created_at"]), prompt: "Created at", id: "id_created_at" %>
          </th>
          <th>Details</th>
          <th>Celebvm</th>
        </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= "$ #{user.price}" %></td>
              <td><%= image_tag user.imageUrl || "", class: "rounded-circle image" %></td>
              <td><%= show_category(user.categories) %></td>
              <td><%= user.created_at.strftime("%d/%m/%Y") %></td>
              <td><%= link_to "View", user_celebvm_detail_path(user.id) %></td>
              <td><%= link_to "Link", "https://celebvm.com/p/#{user.username}", target: "blank" %></td>
            </tr>
          <% end %>
        </tbody>
    </table>
  <% end %>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 custom-pagy">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/homes/crawl.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-3 text-center">Start crawl data</h1>
    <p class="lead">
      <%= form_with url: execute_crawl_path, class: "text-center" do |form| %>
        <div class="wrap-select">
          <%= form.select :type, options_for_select([ "cameo", "celebvm" ], @type), {prompt: "Choose type"}, {class: "form-control width-select"} %>
        </div>
        <%= form.submit "Start crawl", class: "btn btn-primary btn-lg", data: { disable_with: false } %>
      <% end %>
    </p>
    <div id="id_status"><%= render partial: "homes/status", locals: {statuses: @statuses} %></div>
  </div>
</div>

app/views/homes/execute_crawl.js.erb
$("#id_status").html('');
$("#id_status").html('<%= j render(partial: "homes/status", locals: {statuses: @statuses}) %>');

app/views/homes/index.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 wrap-search-box">
    <%= form_with url: cameo_path, method: :get, local: true, id: "id_form_search", class: "form-inline my-2 my-lg-0" do |form| %>
      <%= form.text_field :keyword, value: params["keyword"], id: "id_keyword", class: "form-control mr-sm-2", placeholder: "Enter name" %>
      <%= form.submit "Search", class: "btn btn-outline-success my-2 my-sm-0", id: "id_submit_search", data: { disable_with: false } %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <%= form_tag root_path, method: :get, id: "id_form_user" do %>
    <table class="table table-bordered">
      <thead class="thead-inverse">
        <tr>
          <th><%= select_tag :name, options_for_select([
              {name: "DESC", id: "desc"}, {name: "ASC", id: "asc"}].map { |obj| [obj[:name], obj[:id]] }, params["name"]), prompt: "Name", id: "id_sort_name" %></th>
          <th>Price</th>
          <th>
            <%= select_tag :numOfRatings, options_for_select([
              {name: "DESC", id: "desc"}, {name: "ASC", id: "asc"}].map { |obj| [obj[:name], obj[:id]] }, params["numOfRatings"]), prompt: "numOfRatings", id: "id_sort_rating" %>
          </th>
          <th>Status</th>
          <th>Image</th>
          <th>Profession</th>
          <th>Category</th>
          <th>
            <%= select_tag :created_at, options_for_select([
            {name: "DESC", id: "desc"}, {name: "ASC", id: "asc"}].map { |obj| [obj[:name], obj[:id]] }, params["created_at"]), prompt: "Created at", id: "id_created_at" %>
          </th>
          <th>Details</th>
          <th>Cameo</th>
        </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= "$ #{user.price / 100}" %></td>
              <td><%= user.numOfRatings %></td>
              <td><%= user.temporarilyUnavailable? ? "Inactive" : "Active" %></td>
              <td><%= image_tag user.imageUrl, class: "rounded-circle image" %></td>
              <td><%= user.profession %></td>
              <td><%= show_category(user.categories) %></td>
              <td><%= user.created_at.strftime("%d/%m/%Y") %></td>
              <td><%= link_to "View", user_detail_path(user._id) %></td>
              <td><%= link_to "Link", "https://cameo.com/#{user.username}", target: "blank" %></td>
            </tr>
          <% end %>
        </tbody>
    </table>
  <% end %>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 custom-pagy">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/homes/search_user.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <table class="table table-bordered">
      <thead class="thead-inverse">
        <%= form_tag root_path, method: :get, id: "id_form_user" do %>
        <tr>
          <th>_id</th>
          <th><%= select_tag :name, options_for_select([
              {name: "DESC", id: "desc"}, {name: "ASC", id: "asc"}].map { |obj| [obj[:name], obj[:id]] }, params["name"]), prompt: "Name", id: "id_sort_name" %></th>
          <th>
            <%= select_tag :numOfRatings, options_for_select([
              {name: "DESC", id: "desc"}, {name: "ASC", id: "asc"}].map { |obj| [obj[:name], obj[:id]] }, params["numOfRatings"]), prompt: "numOfRatings", id: "id_sort_rating" %>
          </th>
          <th>Image</th>
          <th>Category</th>
        </tr>
        <% end %>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= link_to user._id, user_detail_path(user._id) %></td>
              <td><%= user.name %></td>
              <td><%= user.numOfRatings %></td>
              <td><%= image_tag user.imageUrl, class: "rounded-circle image" %></td>
              <td><%= show_category(user.categories) %></td>
            </tr>
          <% end %>
        </tbody>
    </table>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 custom-pagy">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/homes/user_celebvm_detail.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <th>name</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th>username</th>
          <td><%= @user.username %></td>
        </tr>
        <tr>
          <th>Image</th>
          <td><%= image_tag @user.imageUrl, class: "rounded-circle image" %></td>
        </tr>
        <tr>
          <th>price</th>
          <td>$ <%= @user.price %></td>
        </tr>
        <tr>
          <th>Category</th>
          <td><%= show_category(@user.categories) %></td>
        </tr>
        <tr>
          <th>Created at</th>
          <td><%= @user.created_at %></td>
        </tr>
        <tr>
          <th>Celebvm</th>
          <td><%= link_to "Link", "https://celebvm.com/p/#{@user.username}", target: "blank" %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/homes/user_detail.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <th>_id</th>
          <td><%= @user._id %></td>
        </tr>
        <tr>
          <th>name</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th>username</th>
          <td><%= @user.username %></td>
        </tr>
        <tr>
          <th>engagement_speed</th>
          <td><%= @user.engagement_speed %></td>
        </tr>
        <tr>
          <th>engagement_volume</th>
          <td><%= @user.engagement_volume %></td>
        </tr>
        <tr>
          <th>engagement_score</th>
          <td><%= @user.engagement_score %></td>
        </tr>
        <tr>
          <th>firstOrderCompletedAt</th>
          <td><%= @user.firstOrderCompletedAt %></td>
        </tr>
        <tr>
          <th>averageMillisecondsToComplete</th>
          <td><%= @user.averageMillisecondsToComplete %></td>
        </tr>
        <tr>
          <th>Image</th>
          <td><%= image_tag @user.imageUrl, class: "rounded-circle image" %></td>
        </tr>
        <tr>
          <th>imageUrlKey</th>
          <td><%= @user.imageUrlKey %></td>
        </tr>
        <tr>
          <th>numOfRatings</th>
          <td><%= @user.numOfRatings %></td>
        </tr>
        <tr>
          <th>averageRating</th>
          <td><%= @user.averageRating %></td>
        </tr>
        <tr>
          <th>price</th>
          <td><%= @user.price %></td>
        </tr>
        <tr>
          <th>profession</th>
          <td><%= @user.profession %></td>
        </tr>
        <tr>
          <th>temporarilyUnavailable</th>
          <td><%= temporarilyUnavailable?(@user.temporarilyUnavailable) %></td>
        </tr>
        <tr>
          <th>bio</th>
          <td><%= @user.bio %></td>
        </tr>
        <tr>
          <th>Category</th>
          <td><%= show_category(@user.categories) %></td>
        </tr>
        <tr>
          <th>Created at</th>
          <td><%= @user.created_at %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <a class="navbar-brand" href="/">Home</a>
  <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
      aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavId">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Services</a>
        <div class="dropdown-menu" aria-labelledby="dropdownId">
          <%= link_to  "Statistic stars", statistic_path, class: "dropdown-item" %>
          <%= link_to  "Export excel", export_data_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Cameo</a>
        <div class="dropdown-menu" aria-labelledby="dropdownId">
          <%= link_to  "Cameo", cameo_path, class: "dropdown-item" %>
          <%= link_to  "Cameo category", category_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Celebvm</a>
        <div class="dropdown-menu" aria-labelledby="dropdownId">
          <%= link_to  "Celebvm", celebvm_path, class: "dropdown-item" %>
          <%= link_to  "Celebvm category", category_celebvm_path, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>Starsona Tools</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/statistic_star/_data.html.erb
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <table class="table table-bordered">
    <thead class="thead-inverse">
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th><%= datetime_range(start_time, end_time) %></th>
      </tr>
    </thead>
    <tbody>
      <% categories.each do |category| %>
        <tr>
          <td scope="row"><%= link_to category.id, category_detail_path(category) %></td>
          <td><%= category.name %></td>
          <td><%= category.users.size %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 custom-pagy">
  <%== pagy_bootstrap_nav(pagy) %>
</div>

app/views/statistic_star/index.html.erb
<div class="row statistic-bottom">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
    <%= form_with url: statistic_path, method: :get, local: true do |form| %>
      <div class="form-group">
        <label><h4>Choose datetime range</h4></label>
        <%= form.text_field :date_range, id: "id_date_range", "data-datetime": datetime_range(@start_time, @end_time), class: "form-control text-center", placeholder: "Choose datetime range" %>
      </div>
      <div class="form-group">
        <label><h4>Choose web type</h4></label>
        <%= form.select :type, options_for_select([ "cameo", "celebvm" ], @type), {prompt: "Choose type"}, {class: "form-control"} %>
      </div>
      <%= form.submit "Search", class: "btn btn-primary", data: { disable_with: false } %>
    <% end %>
  </div>
</div>
<div id="id_statistic_stars" class="row">
  <%= render partial: "statistic_star/data", locals: {pagy: @pagy, categories: @categories, start_time: @start_time, end_time: @end_time} %>
</div>